// backend/src/middleware/auth.ts
import { Request, Response, NextFunction } from "express";
import jwt, { JwtPayload } from "jsonwebtoken";

export interface AuthRequest extends Request {
  user?: {
    id: string;
    email: string;
  };
}

/**
 * Middleware: Verifies JWT tokens generated by our backend (not Supabase)
 */
export const authenticateToken = (
  req: AuthRequest,
  res: Response,
  next: NextFunction
) => {
  try {
    const authHeader = req.headers["authorization"];
    const token = authHeader && authHeader.split(" ")[1];

    if (!token) {
      return res.status(401).json({ error: "Authorization token missing" });
    }

    const jwtSecret = process.env.JWT_SECRET;
    if (!jwtSecret) {
      console.error("❌ JWT_SECRET is not configured in environment");
      return res.status(500).json({ error: "Server misconfiguration" });
    }

    // Verify the token and extract payload
    const decoded = jwt.verify(token, jwtSecret) as JwtPayload;

    if (!decoded || !decoded.userId) {
      return res.status(403).json({ error: "Invalid token payload" });
    }

    // Attach the user info to the request object
    req.user = {
      id: decoded.userId,
      email: decoded.email || "",
    };

    next();
  } catch (error: any) {
    console.error("❌ JWT verification failed:", error.message);
    return res.status(403).json({ error: "Invalid or expired token" });
  }
};
