// backend/src/middleware/auth.ts
import { Request, Response, NextFunction } from "express";
import jwt, { JwtPayload } from "jsonwebtoken";

export interface AuthRequest extends Request {
  user?: {
    id: string;
    email: string;
  };
}

/**
 * Middleware: Verifies JWT tokens generated by either:
 *  - AlphaForge backend (custom JWT_SECRET)
 *  - Supabase (service JWTs)
 */
export const authenticateToken = async (
  req: AuthRequest,
  res: Response,
  next: NextFunction
) => {
  try {
    const authHeader = req.headers["authorization"];
    const token = authHeader && authHeader.split(" ")[1];

    if (!token) {
      return res.status(401).json({ error: "Authorization token missing" });
    }

    const jwtSecret = process.env.JWT_SECRET;
    const supabaseJwtSecret = process.env.SUPABASE_JWT_SECRET;

    if (!jwtSecret && !supabaseJwtSecret) {
      console.error("❌ Missing JWT secret configuration");
      return res.status(500).json({ error: "Server misconfiguration" });
    }

    let decoded: JwtPayload | null = null;

    try {
      // Try verifying backend-issued JWT first
      decoded = jwt.verify(token, jwtSecret!) as JwtPayload;
    } catch (err) {
      // If it fails, try Supabase JWT
      if (supabaseJwtSecret) {
        try {
          decoded = jwt.verify(token, supabaseJwtSecret) as JwtPayload;
        } catch (err2) {
          console.error("❌ Token verification failed for both backend and Supabase:", (err2 as Error).message);
          return res.status(403).json({ error: "Invalid or expired token" });
        }
      } else {
        console.error("❌ Invalid token (no Supabase secret fallback):", (err as Error).message);
        return res.status(403).json({ error: "Invalid or expired token" });
      }
    }

    if (!decoded) {
      return res.status(403).json({ error: "Invalid or expired token" });
    }

    // Detect possible ID/email fields from various payload formats
    const userId = decoded.userId || decoded.sub || decoded.id;
    const email = decoded.email || decoded.user_email || decoded.email_id || "";

    if (!userId) {
      console.error("❌ Invalid JWT payload — missing userId:", decoded);
      return res.status(403).json({ error: "Invalid token payload" });
    }

    req.user = { id: userId.toString(), email };
    next();
  } catch (error: any) {
    console.error("❌ JWT verification failed:", error.message);
    return res.status(403).json({ error: "Invalid or expired token" });
  }
};
